CLASS zrap110_travel_event_handl_04b DEFINITION
  PUBLIC
  FINAL FOR EVENTS OF ZRAP110_R_TRAVELTP_04B
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zrap110_travel_event_handl_04b IMPLEMENTATION.
ENDCLASS.
